## Python and Numpy

We aim to implement the linear algebra concepts using Python. These Python implementations will include vectors, matrices, and some of their respective operations. Additionally, we will again look at problems like solving systems of linear equations using linear algebra.

To perform these linear algebra tasks in Python, we will work with NumPy, a popular numerical computing library. In addition to various built-in linear algebra capabilities, NumPy also works very well with other popular Python libraries used for data science applications such as pandas, SciPy (NumPy’s parent library), and Matplotlib.

### Using NumPy Arrays

The core of using NumPy effectively for linear algebra is using NumPy arrays. NumPy arrays are n-dimensional array data structures that can be used to represent both vectors (1-dimensional array) and matrices (2-dimensional arrays).

A Numpy array is initialized using the np.array() function, and including a Python list argument or Python nested list argument for arrays with more than one dimension.

In [3]:
import numpy as np

v = np.array([1, 2, 3, 4, 5, 6])
v

array([1, 2, 3, 4, 5, 6])

We can also create a matrix, wich is the equivalent of a two-dimensional Numpy array, using a nested Python list:

In [4]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

Matrices can also be created by combining existing vectors using the  np.column_stack() function:

In [5]:
v = np.array([-2,-2,-2,-2])
u = np.array([0,0,0,0])
w = np.array([3,3,3,3])

A = np.column_stack((v,u,w))
A

array([[-2,  0,  3],
       [-2,  0,  3],
       [-2,  0,  3],
       [-2,  0,  3]])

To access the shape of a matrix or vector once it's been created as a NumPy array, we call the .shape attribute of the array variable:

In [6]:
A = np.array([[1,2],[3,4]])
A.shape

(2, 2)

To access individual elements in a NumPy array, we can index the array using square brackets. Unlike regular Python lists, we can index into all dimension in a single square bracket, separating the dimension indices with commas.

Thus in order to index the element equal to 2 in matrix A:

In [7]:
A = np.array([[1,2],[3,4]])
A[0,1]

2

The first index accesses the specific row, while the second index accesses the specific column. Note that rows and columns are zero-indexed.

We can select a subset or entire dimension of a Numpy array using a colon. For example, if we want the entire second column of a matrix, we can index the second column and use an empty colon to select every row as such:

In [8]:
A = np.array([[1,2],[3,4]])
A[:,1]

array([2, 4])

Note that [2, 4] is a column vector, but it outputs in the terminal horizontally.

In [9]:
# Given vectors
vector_1 = np.array([-2,-6,2,3])
vector_2 = np.array([4,1,-3,8])
vector_3 = np.array([5,-7,9,0])

matrix = np.column_stack((vector_1, vector_2, vector_3))

print(matrix)

print(matrix.shape)

print(matrix[:,2])

[[-2  4  5]
 [-6  1 -7]
 [ 2 -3  9]
 [ 3  8  0]]
(4, 3)
[ 5 -7  9  0]


### Using NumPy for Linear Algebra Operations

Now that we know how to use NumPy arrays to create vectors and matrices, we can learn how to perform various linear algebra operations using Python.

To multiply a vector or matrix by a scalar, we use inbuilt Python multiplication between the NumPy array and the scalar:

In [10]:
A = np.array([[1,2],[3,4]])
4 * A

array([[ 4,  8],
       [12, 16]])

To add equally sized vectors or matrices, we can againg use inbuilt Python addition between the NumPy arrays.

In [11]:
A = np.array([[1,2],[3,4]])
B = np.array([[-4,-3],[-2,-1]])
A + B

array([[-3, -1],
       [ 1,  3]])

Vector dot products can be computed using the np.dot() function:

In [12]:
v = np.array([-1,-2,-3])
u = np.array([2,2,2])

np.dot(v,u)

-12

Matrix multiplication is computed using either the np.matmul() function or using the @ symbol as shorthand. It is important to note that using the typical Python multiplication symbol * will result in an elementwise multiplication instead.

In [13]:
A = np.array([[1,2],[3,4]])
B = np.array([[-4,-3],[-2,-1]])

# one way
np.matmul(A,B)

# another
A@B

array([[ -8,  -5],
       [-20, -13]])

1. Calculate the following equation using NumPy:
$$
D=4A−2BD
$$

2. Save your equation to a variable called D and print it in the output terminal.

In [14]:
# Given
# 2 x 3 matrix
A = np.array([[2,3,-4], [-2, 1, -3]])
# 2 x 3 matrix
B = np.array([[1,-1,4], [3,-3,3]])
# 3 x 2 matrix
C = np.array([[1, 2], [3, 4], [5, 6]])

# Calculate D = 4A - 2B
D = 4 * A - 2 * B
D

array([[  6,  14, -24],
       [-14,  10, -18]])

Calculate the following matrix multiplication equation using NumPy:

E=ACE = ACE=AC

Save your equation to a variable called E and print it in the output terminal. Try calculating by hand before or after using Python to verify you understand how the operation works!

What is the shape of our resulting matrix? Why is this?


In [15]:
E = A@C
E

array([[ -9,  -8],
       [-14, -18]])

Calculate the following matrix multiplication equation using NumPy:

F=CA

Save your equation to a variable called F and print it in the output terminal. Try calculating by hand before or after using Python to verify you understand how the operation works!

What is the shape of our resulting matrix? Is the shape of matrix F different from the shape of matrix E? Why is this?


In [16]:
F = C@A
F

array([[ -2,   5, -10],
       [ -2,  13, -24],
       [ -2,  21, -38]])

This time the resulting matrix is 3x3 because matrix C has three rows and matrix B has three columns.

### Special Matrices

In addition to having built-in support for many linear algebra-related operations, Let’s see how NumPy can create special matrices, such as the identity matrix. 

An identity matrix can be constructed using the np.eye() functions, which takes an integer argument that determines the n x n size of the square identity matrix.

In [17]:
# 4x4 identity matrix
identity = np.eye(4)
identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

A matrix or vector of all zeros can be constructed using the np.zeros() function, which takes in a tuple argument for the shape of the NumPy array filled with zeros.

In [18]:
# 5-element vector of zeros
zero_vector = np.zeros((5))
zero_vector

array([0., 0., 0., 0., 0.])

In [19]:
# 3x2 matrix of zeros
zero_matrix = np.zeros((3,2))
zero_matrix

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

The transpose of a matrix can be accessed using the .T attribute of a NumPy array as shown below:

In [20]:
A = np.array([[1,2],[3,4]])
A_transpose = A.T
A_transpose

array([[1, 3],
       [2, 4]])

two NumPy arrays are given, A and B, representing two 3x3 matrices. Print out the matrix product of AB and the matrix product of BA.

What does this say about the relationship between matrix A and matrix B?

In [21]:
A = np.array([[1,-1,1], [0,1,0], [-1,2,1]])
B = np.array([[0.5,1.5,-0.5], [0,1,0], [0.5,-0.5,0.5]])

print(A@B)
print(B@A)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Since the matrix product of A and B results in the identity matrix, they are inverses of each other.

Print out the transpose of both matrix A and matrix B. What is the first row of each transposed matrix?

In [22]:
print(A.T)
print(B.T)

[[ 1  0 -1]
 [-1  1  2]
 [ 1  0  1]]
[[ 0.5  0.   0.5]
 [ 1.5  1.  -0.5]
 [-0.5  0.   0.5]]


### Additional Linear Algebra Operations

The “norm” (or length/magnitude) of a vector can be found using np.linalg.norm():

In [23]:
v = np.array([2,-4,1])
v_norm = np.linalg.norm(v)
v_norm

4.58257569495584

The inverse of a square matrix, if one exists, can be found using np.linalg.inv():

In [24]:
A = np.array([[1,2],[3,4]])
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

We can actually solve for unknown variables in a system on linear equations in Ax=b form using np.linalg.solve(), which takes in the A and b parameters.

In [25]:
'''
x + 4y -  z = -1
-x - 3y + 2z =  2
2x -  y - 2z = -2
'''

# We convert to Ax=b form and solve:

# Each array in A is an equation from the above system of equations
A = np.array([[1,4,-1],[-1,-3,2],[2,-1,-2]])

# The solution to each equation
b = np.array([-1,2,-2])

# Solve for x, y, and z
x, y, z = np.linalg.solve(A, b)

x, y, z

(0.0, 0.0, 1.0)

We have a system of equations. Let’s put this in the form Ax=b and solve the system using NumPy.

First, let’s define A using a NumPy array. Save this NumPy array in a variable called A. When you define A, pay attention to the coefficients in each equation.


In [26]:
'''
4x + z = 2
-y + 2z - 3x = 0
.5y - x - 1.5z = -4
'''
A = np.array([[4,0,1],[-3,-1,2],[-1,.5,-1.5]])
b = np.array([2,0,-4])
x, y, z = np.linalg.solve(A, b)

x, y, z

(6.0, -62.0, -22.0)

### Transforming a vector using NumPy

When thinking in terms of basis vectors, I prefer to break out the basis vectors and
then compose them together into a matrix. Just note you will need to transpose, or
swap the columns and rows. This is because NumPy’s array() function will do the
opposite orientation we want, populating each vector as a row rather than a column.

In [27]:
from numpy import array

# Declare i-hat and j-hat
i_hat = array([2,0])
j_hat = array([0,3])

# Compose basis matrix using i-hat and j-hat
# also need to transpose rows into columns
basis = array([i_hat, j_hat]).transpose()

# Declare vector v
v = array([2,1])

# Create a new vector
# by transforming v with dot product
new_v = basis.dot(v)

print(new_v)

[4 3]


https://www.evernote.com/shard/s468/sh/9db8c9c8-ac87-66b3-febb-efd02d165282/zcyGK36a7KA1_zWFbjIRf4TVz-qDovv-ewWyUwhI_ifLPKpErm4mxUzvDA

Here is an example that jumps things up a notch. Let’s take vector v of value [2, 1]. i
and j start at [1, 0] and [0, 1], but then are transformed and land at [2, 3] and [2, -1].
What happens to v ?

In [28]:
# Declare i-hat and j-hat
i_hat = array([2,3])
j_hat = array([2,-1])

# Compose basis matrix using i-hat and j-hat
# Also need to transpose rows into columns
basis = array([i_hat, j_hat]).T

# Declare vector v
v = array([2,1])

# Transform v with dot product
new_v = basis.dot(v)

print(new_v)

[6 5]


https://www.evernote.com/shard/s468/sh/d85298b3-9bca-ad6c-42f7-06d897515872/AGu6ogZ3LrPiJCRXKT0hfa9KaaruaLTHG0dXv1vUVh8bLvMm63fP5adwrg

A lot has happened here. Not only did we scale i and j and elongate vector v . We
actually sheared, rotated, and flipped space, too. You know space was flipped when i
and j change places in their clockwise orientation, and we will learn how to detect
this with determinants later in this chapter.

### Matrix Multiplication

We learned how to multiply a vector and a matrix, but what exactly does multiply two matrices accomplish? Think of matrix multiplication as applying multiple transformations to a vector space. Each transformation is like a function, where we apply the innermost first and then we apply each subsequent transformation outwards.

In [29]:
## Combining two transformations
from numpy import array

# Transformation 1
i_hat1 = array([0, 1])
j_hat1 = array([-1, 0])
transform1 = array([i_hat1,j_hat1]).transpose()

# Transformation 2
i_hat2 = array([1, 0])
j_hat2 = array([1, 1])
transform2 = array([i_hat2, j_hat2]).transpose()

# Combine Transformations
combined = transform2 @ transform1

# Test
print("COMBINED MATRIX:\n {}".format(combined))

v = array([1, 2])
print(combined.dot(v))


COMBINED MATRIX:
 [[ 1 -1]
 [ 1  0]]
[-1  1]


Note that we also could have applied each transformation individually to vector v
and still have gotten the same result. If you replace the last line with these three lines
applying each transformation, you will still get [-1, 1] on that new vector:

In [30]:
rotated = transform1.dot(v)
sheered = transform2.dot(rotated)
print(sheered)

[-1  1]


Note that the order you apply each transformation matters! If we apply transfor
mation1 on transformation2 , we get a different result of [-2, 3]. So matrix dot products are not commutative, meaning you cannot flip
the order and expect the same result!

In [31]:
# Transformation 1
i_hat1 = array([0, 1])
j_hat1 = array([-1, 0])
transform1 = array([i_hat1, j_hat1]).transpose()
# Transformation 2
i_hat2 = array([1, 0])
j_hat2 = array([1, 1])
transform2 = array([i_hat2, j_hat2]).transpose()
# Combine Transformations, apply sheer first and then rotation
combined = transform1 @ transform2
# Test
print("COMBINED MATRIX:\n {}".format(combined))
v = array([1, 2])
print(combined.dot(v))

COMBINED MATRIX:
 [[ 0 -1]
 [ 1  1]]
[-2  3]


### Determinants

Determinants describe how much a sample area in a vector space changes in scale with linear transformations.

In [32]:
from numpy.linalg import det
from numpy import array

i_hat = array([3, 0])
j_hat = array([0, 2])

basis = array([i_hat, j_hat]).transpose()

determinant = det(basis)

print(determinant)

6.0


Simple shears and rotations should not affect the determinant, as the area will not change. But scaling will increase or decrease the determinant, as that will increase/decrease the sampled area.When the orientation flips ( i , j swap clockwise positions), then the determinant will be negative.

> *But by far the most critical piece of information the determinant tells you is whether
the transformation is linearly dependent. If you have a determinant of 0, that means
all of the space has been squished into a lesser dimension.*

https://www.evernote.com/shard/s468/sh/bcd36bff-9793-b0e3-0b24-1f08874638cd/hztsNDbS7SR597Y_vlI4SQb6APW3i-Ya7oPdMvcdERu06inHGQDjFEtvtQ

In [33]:
from numpy.linalg import det
from numpy import array

i_hat = array([-2, 1])
j_hat = array([3, -1.5])

basis = array([i_hat, j_hat]).transpose()

determinant = det(basis)

print(determinant)

0.0


So testing for a 0 determinant is highly helpful to determine if a transformation
has linear dependence. `When you encounter this you will likely find a difficult or
unsolvable problem on your hands.`

### Special Types of Matrices

#### Square Matrix
The square matrix is a matrix that has an equal number of rows and columns. They are primarily used to represent linear transformations and are a requirement for many operations like eigendecomposition.

#### Identity Matrix
The identity matrix is a square matrix that has a diagonal of 1s while the other values are 0.

What’s the big deal with identity matrices? Well, when you have an identity matrix, you essentially have `undone a transformation` and found your starting basis vectors.This will play a big role in solving systems of equations.

#### Inverse Matrix
An inverse matrix is a matrix that undoes the transformation of another matrix. The inverse of matrix $A$ is called ${}A^{-1}$ . When we perform matrix multiplication between ${}A^{-1}$ and $A$, we end up with an `identity matrix`.

#### Diagonal Matrix
Similar to the identity matrix is the diagonal matrix, which has a diagonal of nonzero values while the rest of the values are 0. Diagonal matrices are desirable in certain computations because they represent `simple scalars` being applied to a vector space. It shows up in some linear algebra operations.

#### Triangular Matrix
Similar to the diagonal matrix is the triangular matrix, which has a diagonal of nonzero values in front of a triangle of values, while the rest of the values are 0.

Triangular matrices are desirable in many numerical analysis tasks, because they typically are easier to solve in systems of equations. They also show up in certain decomposition tasks like LU Decomposition.

### Systems of Equations and Inverse Matrices

One of the basic use cases for linear algebra is solving systems of equations. It is also
a good application to learn about inverse matrices. Let’s say you are provided with the
following equations and you need to solve for x, y, and z:
$$
4x + 2y + 4z = 44\\
5x + 3y + 7z = 56\\
9x + 3y + 6z = 72\\
$$

You can try manually experimenting with different algebraic operations to isolate the
three variables, but if you want a computer to solve it you will need to express this
problem in terms of matrices as shown next. Extract the coefficients into matrix A,
the values on the right side of the equation into matrix B, and the unknown variables
into matrix X:
$$
A =
\left[
\begin{matrix}
4&2&4\\
5&3&7\\
9&3&6
\end{matrix}
\right]
$$

$$
B =
\left[
\begin{matrix}
44\\
56\\
72
\end{matrix}
\right]
$$

$$
X =
\left[
\begin{matrix}
x\\
y\\
z
\end{matrix}
\right]
$$


The function for a linear system of equations is $AX = B$. We need to transform matrix $A$ with some other matrix $X$ that will result in matrix B:

$$
AX = B\\
{}A^{-1} AX = {}A^{-1} B\\
X = {}A^{-1} B
$$

To calculate the inverse of matrix A, we probably use a computer rather than search‐
ing for solutions by hand using Gaussian elimination, which we will not venture into
in this book. Here is the inverse of matrix A:

In [34]:
from sympy import *

# 4x + 2y + 4z = 44
# 5x + 3y + 7z = 56
# 9x + 3y + 6z = 72

A = Matrix([
[4, 2, 4],
[5, 3, 7],
[9, 3, 6]
])

# dot product between A and its inverse
# will produce identity function
inverse = A.inv()
identity = inverse * A #in SymPy we use the asterisk * rather than @

print("INVERSE: {}".format(inverse))
print("IDENTITY: {}".format(identity))

B = Matrix([
44,
56,
72
])

X = A.inv() * B

print(X)

INVERSE: Matrix([[-1/2, 0, 1/3], [11/2, -2, -4/3], [-2, 1, 1/3]])
IDENTITY: Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
Matrix([[2], [34], [-8]])


In [35]:
from numpy import array
from numpy.linalg import inv
# 4x + 2y + 4z = 44
# 5x + 3y + 7z = 56
# 9x + 3y + 6z = 72
A = array([
[4, 2, 4],
[5, 3, 7],
[9, 3, 6]
])
B = array([
44,
56,
72
])
X = inv(A).dot(B)
print(X) # [ 2. 34. -8.]

[ 2. 34. -8.]


### Eigenvectors and Eigenvalues

`Matrix decomposition` is breaking up a matrix into its basic components, much like
factoring numbers (e.g., 10 can be factored to 2 × 5).

Matrix decomposition is helpful for tasks like finding inverse matrices and calculating
determinants, as well as linear regression. There are many ways to decompose a matrix, but let’s focus on a common method called eigendecomposition,
which is often used for machine learning and principal component analysis.

In eigendecomposition, there are two components: the eigenvalues denoted by
lambda λ and eigenvector by v shown in Figure 4-24.

https://www.evernote.com/shard/s468/sh/d7bc2ee9-0d1e-3c6f-9147-5d3ba7960bab/uAQy7f3RTLv5NByhDVoImWD2nA0RuZdLljZFT4v6ygwZpc9yp_ectgdqbg

If we have a square matrix A, it has the following eigenvalue equation:
Av = λv

If A is the original matrix, it is composed of eigenvector v and eigenvalue λ . There is
one eigenvector and eigenvalue for each dimension of the parent matrix, and not all
matrices can be decomposed into an eigenvector and eigenvalue. Sometimes complex
(imaginary) numbers will even result.

In [36]:
from numpy import array, diag
from numpy.linalg import eig, inv

A = array([
[1, 2],
[4, 5]
])

eigenvals, eigenvecs = eig(A)
print("EIGENVALUES")
print(eigenvals)
print("\nEIGENVECTORS")
print(eigenvecs)

EIGENVALUES
[-0.46410162  6.46410162]

EIGENVECTORS
[[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]


So how do we rebuild matrix A from the eigenvectors and eigenvalues? Recall this
formula:
Av = λv
We need to make a few tweaks to the formula to reconstruct A:
A = QΛQ −1
In this new formula, Q is the eigenvectors, Λ is the eigenvalues in diagonal form,
and Q −1 is the inverse matrix of Q . Diagonal form means the vector is padded into
a matrix of zeroes and occupies the diagonal line in a similar pattern to an identity
matrix.

In [37]:
from numpy import array, diag
from numpy.linalg import eig, inv
A = array([
[1, 2],
[4, 5]
])

eigenvals, eigenvecs = eig(A)

print("EIGENVALUES")
print(eigenvals)

print("\nEIGENVECTORS")
print(eigenvecs)

print("\nREBUILD MATRIX")

Q = eigenvecs
R = inv(Q)
L = diag(eigenvals)
B = Q @ L @ R

print(B)


EIGENVALUES
[-0.46410162  6.46410162]

EIGENVECTORS
[[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]

REBUILD MATRIX
[[1. 2.]
 [4. 5.]]


In [38]:
import numpy as np

A = np.array([[2,-3,1],[-2,-1,4],[0,2,2]])
B = np.array([[3,-2,1],[1,-1,2],[-2,2,0]])

C = A@B
C

array([[  1,   1,  -4],
       [-15,  13,  -4],
       [ -2,   2,   4]])

In [39]:
A = np.array([3,-2,2])
B = np.array([1,2,-2])
C = 5*A - 2*B
C

array([ 13, -14,  14])

In [40]:
from numpy import array
from numpy.linalg import inv
# 2x - 3y + z = 2
# 3x + y + z = -1
# -x - 2y - z = 1
A = array([
[2, -3, 1],
[3, 1, 1],
[-1, -2, -1]
])
B = array([
2,
-1,
1
])
X = inv(A).dot(B)
print(X)

[-0.33333333 -0.66666667  0.66666667]


In [41]:
A = np.array([[2, 3], [-2, 0]])
B = np.array([[1,-2], [3,1]])
C = 4 * A - B
C

array([[  7,  14],
       [-11,  -1]])

In [42]:
v = np.array([-2,-3,0,5,1])
v_norm = np.linalg.norm(v)
v_norm

6.244997998398398

In [44]:
from sympy import * 

x = Symbol('x')
solve(-14.4*(x**2)+71.8*x+5.083, x)

[-0.0698162934055920, 5.05592740451670]