## Python and Numpy

We aim to implement the linear algebra concepts using Python. These Python implementations will include vectors, matrices, and some of their respective operations. Additionally, we will again look at problems like solving systems of linear equations using linear algebra.

To perform these linear algebra tasks in Python, we will work with NumPy, a popular numerical computing library. In addition to various built-in linear algebra capabilities, NumPy also works very well with other popular Python libraries used for data science applications such as pandas, SciPy (NumPy’s parent library), and Matplotlib.

### Using NumPy Arrays

The core of using NumPy effectively for linear algebra is using NumPy arrays. NumPy arrays are n-dimensional array data structures that can be used to represent both vectors (1-dimensional array) and matrices (2-dimensional arrays).

A Numpy array is initialized using the np.array() function, and including a Python list argument or Python nested list argument for arrays with more than one dimension.

In [4]:
import numpy as np

v = np.array([1, 2, 3, 4, 5, 6])
v

array([1, 2, 3, 4, 5, 6])

We can also create a matrix, wich is the equivalent of a two-dimensional Numpy array, using a nested Python list:

In [5]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

Matrices can also be created by combining existing vectors using the  np.column_stack() function:

In [6]:
v = np.array([-2,-2,-2,-2])
u = np.array([0,0,0,0])
w = np.array([3,3,3,3])

A = np.column_stack((v,u,w))
A

array([[-2,  0,  3],
       [-2,  0,  3],
       [-2,  0,  3],
       [-2,  0,  3]])

To access the shape of a matrix or vector once it's been created as a NumPy array, we call the .shape attribute of the array variable:

In [7]:
A = np.array([[1,2],[3,4]])
A.shape

(2, 2)

To access individual elements in a NumPy array, we can index the array using square brackets. Unlike regular Python lists, we can index into all dimension in a single square bracket, separating the dimension indices with commas.

Thus in order to index the element equal to 2 in matrix A:

In [8]:
A = np.array([[1,2],[3,4]])
A[0,1]

2

The first index accesses the specific row, while the second index accesses the specific column. Note that rows and columns are zero-indexed.

We can select a subset or entire dimension of a Numpy array using a colon. For example, if we want the entire second column of a matrix, we can index the second column and use an empty colon to select every row as such:

In [9]:
A = np.array([[1,2],[3,4]])
A[:,1]

array([2, 4])

Note that [2, 4] is a column vector, but it outputs in the terminal horizontally.

In [11]:
# Given vectors
vector_1 = np.array([-2,-6,2,3])
vector_2 = np.array([4,1,-3,8])
vector_3 = np.array([5,-7,9,0])

matrix = np.column_stack((vector_1, vector_2, vector_3))

print(matrix)

print(matrix.shape)

print(matrix[:,2])

[[-2  4  5]
 [-6  1 -7]
 [ 2 -3  9]
 [ 3  8  0]]
(4, 3)
[ 5 -7  9  0]


### Using NumPy for Linear Algebra Operations

Now that we know how to use NumPy arrays to create vectors and matrices, we can learn how to perform various linear algebra operations using Python.

To multiply a vector or matrix by a scalar, we use inbuilt Python multiplication between the NumPy array and the scalar:

In [12]:
A = np.array([[1,2],[3,4]])
4 * A

array([[ 4,  8],
       [12, 16]])

To add equally sized vectors or matrices, we can againg use inbuilt Python addition between the NumPy arrays.

In [13]:
A = np.array([[1,2],[3,4]])
B = np.array([[-4,-3],[-2,-1]])
A + B

array([[-3, -1],
       [ 1,  3]])

Vector dot products can be computed using the np.dot() function:

In [14]:
v = np.array([-1,-2,-3])
u = np.array([2,2,2])

np.dot(v,u)

-12

Matrix multiplication is computed using either the np.matmul() function or using the @ symbol as shorthand. It is important to note that using the typical Python multiplication symbol * will result in an elementwise multiplication instead.

In [16]:
A = np.array([[1,2],[3,4]])
B = np.array([[-4,-3],[-2,-1]])

# one way
np.matmul(A,B)

# another
A@B

array([[ -8,  -5],
       [-20, -13]])

1. Calculate the following equation using NumPy:
$$
D=4A−2BD
$$

2. Save your equation to a variable called D and print it in the output terminal.

In [17]:
# Given
# 2 x 3 matrix
A = np.array([[2,3,-4], [-2, 1, -3]])
# 2 x 3 matrix
B = np.array([[1,-1,4], [3,-3,3]])
# 3 x 2 matrix
C = np.array([[1, 2], [3, 4], [5, 6]])

# Calculate D = 4A - 2B
D = 4 * A - 2 * B
D

array([[  6,  14, -24],
       [-14,  10, -18]])

Calculate the following matrix multiplication equation using NumPy:

E=ACE = ACE=AC

Save your equation to a variable called E and print it in the output terminal. Try calculating by hand before or after using Python to verify you understand how the operation works!

What is the shape of our resulting matrix? Why is this?


In [19]:
E = A@C
E

array([[ -9,  -8],
       [-14, -18]])

Calculate the following matrix multiplication equation using NumPy:

F=CA

Save your equation to a variable called F and print it in the output terminal. Try calculating by hand before or after using Python to verify you understand how the operation works!

What is the shape of our resulting matrix? Is the shape of matrix F different from the shape of matrix E? Why is this?


In [20]:
F = C@A
F

array([[ -2,   5, -10],
       [ -2,  13, -24],
       [ -2,  21, -38]])

This time the resulting matrix is 3x3 because matrix C has three rows and matrix B has three columns.

### Special Matrices

In addition to having built-in support for many linear algebra-related operations, Let’s see how NumPy can create special matrices, such as the identity matrix. 

An identity matrix can be constructed using the np.eye() functions, which takes an integer argument that determines the n x n size of the square identity matrix.

In [21]:
# 4x4 identity matrix
identity = np.eye(4)
identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

A matrix or vector of all zeros can be constructed using the np.zeros() function, which takes in a tuple argument for the shape of the NumPy array filled with zeros.

In [23]:
# 5-element vector of zeros
zero_vector = np.zeros((5))
zero_vector

array([0., 0., 0., 0., 0.])

In [24]:
# 3x2 matrix of zeros
zero_matrix = np.zeros((3,2))
zero_matrix

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

The transpose of a matrix can be accessed using the .T attribute of a NumPy array as shown below:

In [26]:
A = np.array([[1,2],[3,4]])
A_transpose = A.T
A_transpose

array([[1, 3],
       [2, 4]])

two NumPy arrays are given, A and B, representing two 3x3 matrices. Print out the matrix product of AB and the matrix product of BA.

What does this say about the relationship between matrix A and matrix B?

In [27]:
A = np.array([[1,-1,1], [0,1,0], [-1,2,1]])
B = np.array([[0.5,1.5,-0.5], [0,1,0], [0.5,-0.5,0.5]])

print(A@B)
print(B@A)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Since the matrix product of A and B results in the identity matrix, they are inverses of each other.

Print out the transpose of both matrix A and matrix B. What is the first row of each transposed matrix?

In [28]:
print(A.T)
print(B.T)

[[ 1  0 -1]
 [-1  1  2]
 [ 1  0  1]]
[[ 0.5  0.   0.5]
 [ 1.5  1.  -0.5]
 [-0.5  0.   0.5]]


### Additional Linear Algebra Operations

The “norm” (or length/magnitude) of a vector can be found using np.linalg.norm():

In [29]:
v = np.array([2,-4,1])
v_norm = np.linalg.norm(v)
v_norm

4.58257569495584

The inverse of a square matrix, if one exists, can be found using np.linalg.inv():

In [30]:
A = np.array([[1,2],[3,4]])
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

We can actually solve for unknown variables in a system on linear equations in Ax=b form using np.linalg.solve(), which takes in the A and b parameters.

In [31]:
'''
x + 4y -  z = -1
-x - 3y + 2z =  2
2x -  y - 2z = -2
'''

# We convert to Ax=b form and solve:

# Each array in A is an equation from the above system of equations
A = np.array([[1,4,-1],[-1,-3,2],[2,-1,-2]])

# The solution to each equation
b = np.array([-1,2,-2])

# Solve for x, y, and z
x, y, z = np.linalg.solve(A, b)

x, y, z

(0.0, 0.0, 1.0)

We have a system of equations. Let’s put this in the form Ax=b and solve the system using NumPy.

First, let’s define A using a NumPy array. Save this NumPy array in a variable called A. When you define A, pay attention to the coefficients in each equation.


In [36]:
'''
4x + z = 2
-y + 2z - 3x = 0
.5y - x - 1.5z = -4
'''
A = np.array([[4,0,1],[-3,-1,2],[-1,.5,-1.5]])
b = np.array([2,0,-4])
x, y, z = np.linalg.solve(A, b)

x, y, z

(6.0, -62.0, -22.0)

### Transforming a vector using NumPy

When thinking in terms of basis vectors, I prefer to break out the basis vectors and
then compose them together into a matrix. Just note you will need to transpose, or
swap the columns and rows. This is because NumPy’s array() function will do the
opposite orientation we want, populating each vector as a row rather than a column.

In [5]:
from numpy import array

# Declare i-hat and j-hat
i_hat = array([2,0])
j_hat = array([0,3])

# Compose basis matrix using i-hat and j-hat
# also need to transpose rows into columns
basis = array([i_hat, j_hat]).transpose()

# Declare vector v
v = array([2,1])

# Create a new vector
# by transforming v with dot product
new_v = basis.dot(v)

print(new_v)

[4 3]


https://www.evernote.com/shard/s468/sh/9db8c9c8-ac87-66b3-febb-efd02d165282/zcyGK36a7KA1_zWFbjIRf4TVz-qDovv-ewWyUwhI_ifLPKpErm4mxUzvDA

Here is an example that jumps things up a notch. Let’s take vector v of value [2, 1]. i
and j start at [1, 0] and [0, 1], but then are transformed and land at [2, 3] and [2, -1].
What happens to v ?

In [8]:
# Declare i-hat and j-hat
i_hat = array([2,3])
j_hat = array([2,-1])

# Compose basis matrix using i-hat and j-hat
# Also need to transpose rows into columns
basis = array([i_hat, j_hat]).T

# Declare vector v
v = array([2,1])

# Transform v with dot product
new_v = basis.dot(v)

print(new_v)

[6 5]


https://www.evernote.com/shard/s468/sh/d85298b3-9bca-ad6c-42f7-06d897515872/AGu6ogZ3LrPiJCRXKT0hfa9KaaruaLTHG0dXv1vUVh8bLvMm63fP5adwrg

A lot has happened here. Not only did we scale i and j and elongate vector v . We
actually sheared, rotated, and flipped space, too. You know space was flipped when i
and j change places in their clockwise orientation, and we will learn how to detect
this with determinants later in this chapter.

### Matrix Multiplication

We learned how to multiply a vector and a matrix, but what exactly does multiply two matrices accomplish? Think of matrix multiplication as applying multiple transformations to a vector space. Each transformation is like a function, where we apply the innermost first and then we apply each subsequent transformation outwards.

In [2]:
## Combining two transformations
from numpy import array

# Transformation 1
i_hat1 = array([0, 1])
j_hat1 = array([-1, 0])
transform1 = array([i_hat1,j_hat1]).transpose()

# Transformation 2
i_hat2 = array([1, 0])
j_hat2 = array([1, 1])
transform2 = array([i_hat2, j_hat2]).transpose()

# Combine Transformations
combined = transform2 @ transform1

# Test
print("COMBINED MATRIX:\n {}".format(combined))

v = array([1, 2])
print(combined.dot(v))


COMBINED MATRIX:
 [[ 1 -1]
 [ 1  0]]
[-1  1]


Note that we also could have applied each transformation individually to vector v
and still have gotten the same result. If you replace the last line with these three lines
applying each transformation, you will still get [-1, 1] on that new vector:

In [3]:
rotated = transform1.dot(v)
sheered = transform2.dot(rotated)
print(sheered)

[-1  1]


Note that the order you apply each transformation matters! If we apply transfor
mation1 on transformation2 , we get a different result of [-2, 3]. So matrix dot products are not commutative, meaning you cannot flip
the order and expect the same result!

In [4]:
# Transformation 1
i_hat1 = array([0, 1])
j_hat1 = array([-1, 0])
transform1 = array([i_hat1, j_hat1]).transpose()
# Transformation 2
i_hat2 = array([1, 0])
j_hat2 = array([1, 1])
transform2 = array([i_hat2, j_hat2]).transpose()
# Combine Transformations, apply sheer first and then rotation
combined = transform1 @ transform2
# Test
print("COMBINED MATRIX:\n {}".format(combined))
v = array([1, 2])
print(combined.dot(v))

COMBINED MATRIX:
 [[ 0 -1]
 [ 1  1]]
[-2  3]
