## Python and Numpy

We aim to implement the linear algebra concepts using Python. These Python implementations will include vectors, matrices, and some of their respective operations. Additionally, we will again look at problems like solving systems of linear equations using linear algebra.

To perform these linear algebra tasks in Python, we will work with NumPy, a popular numerical computing library. In addition to various built-in linear algebra capabilities, NumPy also works very well with other popular Python libraries used for data science applications such as pandas, SciPy (NumPy’s parent library), and Matplotlib.

### Using NumPy Arrays

The core of using NumPy effectively for linear algebra is using NumPy arrays. NumPy arrays are n-dimensional array data structures that can be used to represent both vectors (1-dimensional array) and matrices (2-dimensional arrays).

A Numpy array is initialized using the np.array() function, and including a Python list argument or Python nested list argument for arrays with more than one dimension.

In [4]:
import numpy as np

v = np.array([1, 2, 3, 4, 5, 6])
v

array([1, 2, 3, 4, 5, 6])

We can also create a matrix, wich is the equivalent of a two-dimensional Numpy array, using a nested Python list:

In [5]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

Matrices can also be created by combining existing vectors using the  np.column_stack() function:

In [6]:
v = np.array([-2,-2,-2,-2])
u = np.array([0,0,0,0])
w = np.array([3,3,3,3])

A = np.column_stack((v,u,w))
A

array([[-2,  0,  3],
       [-2,  0,  3],
       [-2,  0,  3],
       [-2,  0,  3]])

To access the shape of a matrix or vector once it's been created as a NumPy array, we call the .shape attribute of the array variable:

In [7]:
A = np.array([[1,2],[3,4]])
A.shape

(2, 2)

To access individual elements in a NumPy array, we can index the array using square brackets. Unlike regular Python lists, we can index into all dimension in a single square bracket, separating the dimension indices with commas.

Thus in order to index the element equal to 2 in matrix A:

In [8]:
A = np.array([[1,2],[3,4]])
A[0,1]

2

The first index accesses the specific row, while the second index accesses the specific column. Note that rows and columns are zero-indexed.

We can select a subset or entire dimension of a Numpy array using a colon. For example, if we want the entire second column of a matrix, we can index the second column and use an empty colon to select every row as such:

In [9]:
A = np.array([[1,2],[3,4]])
A[:,1]

array([2, 4])

Note that [2, 4] is a column vector, but it outputs in the terminal horizontally.

In [11]:
# Given vectors
vector_1 = np.array([-2,-6,2,3])
vector_2 = np.array([4,1,-3,8])
vector_3 = np.array([5,-7,9,0])

matrix = np.column_stack((vector_1, vector_2, vector_3))

print(matrix)

print(matrix.shape)

print(matrix[:,2])

[[-2  4  5]
 [-6  1 -7]
 [ 2 -3  9]
 [ 3  8  0]]
(4, 3)
[ 5 -7  9  0]
